language: clojure

cache:
  directories:
    - $HOME/.m2

before_script:
  # update lein to latest, https://github.com/technomancy/leiningen/issues/2014#issuecomment-153829977
  - yes y | sudo lein upgrade
  # install nodejs for npm, which is needed for js-beautify
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs nodejs-legacy colordiff
  - sudo npm install -g js-beautify
  # install phantomjs, http://stackoverflow.com/a/36843608/84283
  - sudo npm install -g phantomjs-prebuilt

script: lein test-all
