sudo: true
dist: trusty
language: clojure
notifications:
  email:
  - antonin@hildebrand.cz
  hipchat:
    rooms:
      secure: OQDXsZ8/ppooXuwoEs2EOU1spguOTDM33mJxI4LCPfRAN/tfvfe9M2L/itDuVsVxeoRVsd/amgAcmDGBCMBjzICkmgqzmIxTkKKS6o4I0d4L6DnuNWiu/PpQ934oDOnD/OYwhZpWO/YCHyByp+VFW36iFlLYd14E/uTvmRBgEA/94IG3+S8VWEDjd4NbedGP9hKG8BjXLbx8U2ajIAuvvJIse+2XryZagXoXFLgprAZRAuUFUeIun/HxKs4mcQMgOen7T61b4jtF3dZsMKt133553LCNccpDxnqA5SaBHUPYGvz4lh1M8/mesk42YcMcIO5vvQ+oF//Hmj7cEd8OxsD48CuJUe9iDsuXCNL3OWaPUbsLQQOv2d8PTWv+61/LDILeNvP/0tWGDpp63S0t2zVNg0XpAYxQCcOXLROe3cWIWaFDblFsI6HntY7Ee+3WmvLpvXStMDhIGYdbR8LbvhT9lsT5anobOnLvfBEwbwbcA3FN9VHqYThzi17+CKbteb+NA88xCFy6fvqH+InNY7N2Xaeylpn3+QEefxxfuK40cX92MGxtBUERWdTIXKsOjnQxVAOqxT5w4wkw8j0omVFRqncYS03hxXBLhTG7CO/ca5dpeSD+ngPdi8qSWBUCCD8otx6jVsnQGQUUv/o8YOfOWhuRK8OzJwv0B/DBAbE=
    template:
    - '<a href="%{build_url}">%{repository}#%{build_number}</a>: %{message} (<a href="%{compare_url}">changes</a>)'
    format: html
cache:
  directories:
  - "$HOME/.m2"
before_script:
- yes y | sudo lein upgrade
- curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
- sudo apt-get install -y nodejs colordiff
- sudo npm install -g js-beautify
script: lein test-all
