language: clojure

cache:
  directories:
    - $HOME/.m2

before_script:
  # update lein to latest, https://github.com/technomancy/leiningen/issues/2014#issuecomment-153829977
  - yes y | sudo lein upgrade
  # install nodejs for npm, which is needed for js-beautify
  - curl -sL https://deb.nodesource.com/setup_4.x | sudo -E bash -
  - sudo apt-get install -y nodejs colordiff
  - sudo npm install -g js-beautify
  # install phantomjs
  - mkdir travis-phantomjs
  - wget https://s3.amazonaws.com/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -O $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2
  - tar -xvf $PWD/travis-phantomjs/phantomjs-2.0.0-ubuntu-12.04.tar.bz2 -C $PWD/travis-phantomjs
  - export PATH=$PWD/travis-phantomjs:$PATH

script: lein test-all
